# This is a basic workflow to help you get started with Actions

name: WeatherStation app pipeline

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      #Installs Python version 3.6
      - name: Install Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'
      
      #Sets up a Python virtual enviroment with all necesseary dependencies
      - name: Set up Python virtual environment
        run: | 
           pip install --upgrade pip
           python -m venv testingEnviroment
           testingEnvironment\Scripts\activate
           pip install -r requirements.txt
